# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Tytuł')),
                ('article_text', models.TextField(verbose_name='Treść')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='Autor')),
                ('pub_date', models.DateTimeField(verbose_name='Data dodania')),
                ('image_url', models.URLField(blank=True, verbose_name='Źródło obrazka')),
                ('image', models.ImageField(blank=True, null=True, upload_to='kw/', verbose_name='Zdjęcie')),
                ('article_url', models.URLField(unique=True, verbose_name='Źródło')),
            ],
            options={
                'verbose_name': 'Artykuł',
                'verbose_name_plural': 'Artykuły',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='Nazwa kategorii')),
                ('articles_number', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255, verbose_name='Treść')),
                ('articles_number', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Strona źródłowa',
                'verbose_name_plural': 'Strony źródłowe',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arts.Category', verbose_name='Kategoria'),
        ),
        migrations.AddField(
            model_name='article',
            name='site_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arts.Site', verbose_name='Strona źródłowa'),
        ),
    ]
