# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-29 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0002_auto_20170521_2053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opinion',
            options={'verbose_name': 'Opinia', 'verbose_name_plural': 'Opinie'},
        ),
    ]
